# Numpy practice


In [1]:
import numpy as np

In [6]:
np.random.randint?


In [ ]:
np.random,randint

In [2]:
np.random.randint(1,100)

57

In [30]:
l = np.random.randint(100,size=10)

In [32]:
l

array([90, 30, 68,  2, 47, 72, 96, 48, 93, 62])

In [11]:
l.astype(float)

array([49.,  6., 11.,  9., 99., 27., 43., 86., 32., 18.])

In [27]:
np.random.rand(3,5)

array([[0.97221982, 0.58455349, 0.50362197, 0.48906732, 0.93327257],
       [0.04499327, 0.39478342, 0.72000154, 0.15586753, 0.6802776 ],
       [0.54226092, 0.00740657, 0.70552948, 0.52889353, 0.68521537]])

In [19]:
np.random.rand(10,15)


array([[0.44228056, 0.08632337, 0.5854222 , 0.15614473, 0.14296486,
        0.73837196, 0.68939275, 0.36168705, 0.58909943, 0.70546049,
        0.61442551, 0.28160395, 0.6808122 , 0.12749929, 0.36913421],
       [0.69055347, 0.82477259, 0.34567991, 0.97566053, 0.31313444,
        0.35056672, 0.19493215, 0.46377627, 0.53342809, 0.95677659,
        0.92414081, 0.08234348, 0.84476331, 0.17553967, 0.33446024],
       [0.67556532, 0.01904827, 0.35406764, 0.00545651, 0.60212943,
        0.48383251, 0.45065807, 0.34469057, 0.97418656, 0.44329379,
        0.96573697, 0.46139119, 0.53971391, 0.83439547, 0.2969876 ],
       [0.69419382, 0.17465484, 0.0375156 , 0.56566822, 0.9412184 ,
        0.18426378, 0.56497139, 0.68493983, 0.85492031, 0.56707086,
        0.16927517, 0.96008559, 0.03045995, 0.14335271, 0.4360131 ],
       [0.36009417, 0.98784892, 0.32971871, 0.27031738, 0.79191963,
        0.3850865 , 0.90851948, 0.99706115, 0.61302072, 0.25873449,
        0.2399338 , 0.69141884, 0.79163505, 

In [23]:
np.random.uniform(10,15,size=(4,6))

array([[12.54589601, 14.11797601, 13.01528441, 14.04250892, 11.66964073,
        12.3074051 ],
       [13.4753228 , 14.1186953 , 13.87930817, 12.82702083, 12.56819056,
        11.563865  ],
       [10.7738164 , 12.70138785, 13.15072931, 10.10496779, 12.55813842,
        10.44656601],
       [12.24835998, 10.31828131, 13.2387042 , 11.31509236, 11.33950565,
        12.96921889]])

In [24]:
np.random.randn(10,15)

array([[-0.14915331, -0.84349879,  0.49116049, -0.86771589,  0.24332994,
         0.21852919,  0.65192133, -0.66268847, -0.21418671,  3.01386698,
        -0.46510919, -1.17906485, -0.36967495,  1.1237918 , -0.40518801],
       [ 0.97606559, -0.36681437, -0.47005776,  0.77089365, -0.11227495,
         0.73363703, -0.99291395,  1.13279406, -2.13912808,  1.9761911 ,
         1.2184171 ,  0.26710646, -0.90467633, -1.75972322, -1.65274418],
       [ 0.93948872, -0.27579353, -0.44660731, -0.03024184, -2.11256599,
        -1.18250625,  1.77458102,  0.40080615, -0.68361786, -1.24156219,
         0.9667817 , -0.01696732,  1.57120864, -0.52397641, -0.01012087],
       [-1.10405255, -0.49744891,  0.07365229, -0.29383363, -1.35039033,
         0.98528172,  0.47493944,  0.75073229,  1.53017255, -1.65634636,
         1.19327989, -1.70591972,  0.34146642, -0.70259947,  1.39806465],
       [-0.85920851, -0.43282203, -0.88039063,  0.01644748,  0.99507521,
         0.92218823,  0.48879568,  1.40525218, 

In [25]:
np.random.randn(2,3)

array([[-1.93354693,  0.09388201,  0.54197632],
       [ 1.3357989 ,  2.29390643, -1.7253237 ]])

np.random.randint() - create array within a range and size
np.random.rand()- returns a matrix with specified size with values between 0 and 1, all values follow unifrom distribution
np.random.uniform() - returns uniformly distributed matrix within specified range
np.random.randn() - returns a matrix with specified size with values between 0 and 1, all values follow normal distribution
np.random.normal() -  returns normally distributed matrix within specified range
np.random.shuffle() - to shuffle order of elements in the given nd array( only 0-axis, 1 st and next axes willnot change) 


In [34]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
np.random.shuffle(a)
a

array([16, 18, 12, 11, 10, 15, 17, 19, 13, 14])

In [52]:
a = np.random.randint(1,101,size= (4,6,3))
a

array([[[ 15,  33,  15],
        [  8,  84,  67],
        [ 68,  71,  60],
        [ 92,  51,  43],
        [ 26,  33,  96],
        [ 35,  19,  38]],

       [[ 68,  38,  48],
        [ 76,  82,  84],
        [ 81,  61,  29],
        [  7,  71,  73],
        [ 26,  74,  63],
        [ 14,  30,   4]],

       [[ 91,  51,  83],
        [ 37,  35, 100],
        [  3,  83,  40],
        [ 45,  20,  47],
        [ 65,  32,  36],
        [ 87,  68,  17]],

       [[ 77,  99,   4],
        [ 69,  84,  20],
        [ 54,  31,  55],
        [ 71,  98,  90],
        [ 68,  96,  87],
        [ 12,  59,  58]]])

In [53]:
np.random.shuffle(a)
a

array([[[ 77,  99,   4],
        [ 69,  84,  20],
        [ 54,  31,  55],
        [ 71,  98,  90],
        [ 68,  96,  87],
        [ 12,  59,  58]],

       [[ 15,  33,  15],
        [  8,  84,  67],
        [ 68,  71,  60],
        [ 92,  51,  43],
        [ 26,  33,  96],
        [ 35,  19,  38]],

       [[ 91,  51,  83],
        [ 37,  35, 100],
        [  3,  83,  40],
        [ 45,  20,  47],
        [ 65,  32,  36],
        [ 87,  68,  17]],

       [[ 68,  38,  48],
        [ 76,  82,  84],
        [ 81,  61,  29],
        [  7,  71,  73],
        [ 26,  74,  63],
        [ 14,  30,   4]]])

In [ ]:
Numpy array creation

1. array()
2. arange()
3. linspace()
4. zeros()
5. ones()
6. eye()
7. full()
8. identity()
9. empty()
10. random library

# array attributes:

1. a.ndim  - retuns the dimensions of an array
2. a.shape - return the shape of an array(5,), (2,3,4)
3. a.size - to get total number of elements
4. a.dtype - to get type of array elements
5. a.itemsize - (how many bytes)

In [54]:
a = np.array([10,20,30,40])

In [57]:
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.itemsize)

1
4
(4,)
int32
4


In [58]:
a = np.array([[10,20,30,40],[50,60,70,80]])


In [59]:
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.itemsize)

2
8
(2, 4)
int32
4
